web:
  port: 5010
app:
  name: FasterGerman
  version: 0.0.5
  language-code: en-GB
  # [dev|prod]
  profiles: dev
  questions:
    dir: resources/config/questions
  translations:
    dir: resources/config/i18n

