web:
  port: 5010
app:
  name: FasterGerman
  version: 0.0.5
  language-code: en-GB
  # [dev|prod]
  profiles: dev
  questions:
    dir: resources/config/questions
  translations:
    dir: resources/config/i18n
  chat:
    ratelimit:
      permits: 2
      duration: 10000
    disabled: false
    history_max_tokens: 10000
    input_max_chars: 1000
    prompt: You are a helpful assistant. Answer all questions to the best of your ability in {language}.
    model:
      name: llama3.2 #llama3.1 # gpt-4o-mini
      # use `echo` here to have your chat messages echoed to you.
      provider: ollama # openai