web:
  port: 5010
app:
  name: FasterGerman
  version: 0.0.3
  language-code: en-GB
  # [dev|prod]
  profiles: dev
  preposition-trainer:
      question-src: resources/config/preposition-trainer-default-questions.json
