define:
  &log_level 'DEBUG'
version: 1
formatters:
  simple:
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: *log_level
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: *log_level
    formatter: simple
    filename: output/logs/fastergerman.log
    maxBytes: 409600
    backupCount: 9
loggers:
  fastergerman:
    level: *log_level
    handlers: [console, file]
    propagate: false
root:
  level: *log_level
  handlers: [console, file]